//! Generated, vendored and test code detection.
//!
//! Classification is product-visible: it is what `peek overview` tells an agent to ignore. A hidden
//! heuristic is therefore unacceptable, and these tests assert the documented rule table rule by
//! rule, negatives included. `classify.rs` holds the table; this file is the proof that the code
//! implements the table it documents.

use super::discover_fixture;
use super::support::contains;
use crate::discover::Classification;
use crate::model::RepoPath;

fn path(value: &str) -> RepoPath {
    RepoPath::new(value).expect("valid repository path")
}

fn classify_of(value: &str) -> Classification {
    Classification::of(&path(value), "fn main() {}")
}

fn classify_with(value: &str, source: &str) -> Classification {
    Classification::of(&path(value), source)
}

// --- Rule 1: vendored directories ----------------------------------------------------------------

#[test]
fn a_vendored_directory_makes_the_file_vendored() {
    assert_eq!(
        classify_of("vendor/lib/helper.rs"),
        Classification::Vendored
    );
    assert_eq!(
        classify_of("third_party/legacy.c"),
        Classification::Vendored
    );
    assert_eq!(
        classify_of("crates/x/external/deep/thing.go"),
        Classification::Vendored,
        "the rule matches at any depth"
    );
}

#[test]
fn a_file_named_like_a_vendored_directory_is_not_vendored() {
    // The file name is not a directory component. A hand-written `vendor.rs` in `src/` is the
    // project's own code, and telling an agent to ignore it would be a real error.
    assert_eq!(classify_of("src/vendor.rs"), Classification::Source);
    assert_eq!(classify_of("src/vendor"), Classification::Source);
    assert_eq!(
        classify_of("src/vendor_notes.rs"),
        Classification::Source,
        "the component must match exactly, not as a prefix"
    );
}

#[test]
fn vendored_directory_matching_is_case_insensitive() {
    assert_eq!(classify_of("Vendor/lib/x.rs"), Classification::Vendored);
    assert_eq!(classify_of("THIRD_PARTY/x.c"), Classification::Vendored);
}

// --- Rule 2: generated directories --------------------------------------------------------------

#[test]
fn a_generated_directory_makes_the_file_generated() {
    assert_eq!(classify_of("src/gen/models.rs"), Classification::Generated);
    assert_eq!(
        classify_of("api/__generated__/client.ts"),
        Classification::Generated
    );
}

#[test]
fn vendored_wins_over_generated() {
    // A vendored tree that happens to contain a `gen/` directory is third-party code. That is the
    // more useful answer for an agent deciding what to ignore, and the rule order says so.
    assert_eq!(
        classify_of("vendor/gen/api.rs"),
        Classification::Vendored,
        "rule 1 precedes rule 2, so the more specific exclusion wins"
    );
}

// --- Rule 3: generated header markers ----------------------------------------------------------

#[test]
fn a_generated_header_marker_makes_the_file_generated() {
    for marker in [
        "// @generated",
        "/* Code generated by protoc. */",
        "//! DO NOT EDIT",
        "<!-- automatically generated -->",
    ] {
        assert_eq!(
            classify_with("src/thing.rs", marker),
            Classification::Generated,
            "marker `{marker}` must be recognised"
        );
    }
}

#[test]
fn a_generated_marker_beyond_the_scan_window_is_not_matched() {
    // The scan window is bounded on purpose. A 200 MB data file that mentions "generated by" deep
    // in its body is not generated code, and scanning the whole file would misclassify it.
    let padding = "// padding\n".repeat(Classification::HEADER_SCAN_BYTES / 8);
    let source = format!("{padding}// @generated\n");

    assert!(
        source.len() > Classification::HEADER_SCAN_BYTES,
        "the fixture must exceed the scan window, got {} bytes",
        source.len()
    );
    assert_eq!(
        classify_with("src/data.rs", &source),
        Classification::Source,
        "a marker past the scan window must not classify the file"
    );
}

#[test]
fn a_marker_below_a_short_licence_header_is_still_found() {
    let source = "// Copyright 2026 Example Corp. All rights reserved.\n// SPDX-License-Identifier: MIT\n\n// @generated by protoc\nfn f() {}\n";
    assert!(
        source.len() < Classification::HEADER_SCAN_BYTES,
        "a licence header plus a marker must fit in the window"
    );
    assert_eq!(
        classify_with("src/proto.rs", source),
        Classification::Generated
    );
}

#[test]
fn a_multi_byte_character_at_the_window_boundary_does_not_panic() {
    // Truncation is by character boundary. A naive `&source[..HEADER_SCAN_BYTES]` panics here,
    // and this test is the only thing standing between that panic and a crash on real source.
    let filler = "é".repeat(Classification::HEADER_SCAN_BYTES);
    let source = format!("{filler}\n// @generated\n");

    assert_eq!(
        classify_with("src/unicode.rs", &source),
        Classification::Source
    );
}

// --- Rule 4: generated file names ---------------------------------------------------------------

#[test]
fn a_generated_file_name_makes_the_file_generated_without_reading_it() {
    // These are the languages whose generated output carries no usable header.
    for name in [
        "src/schema_pb2.py",
        "src/service_pb2_grpc.py",
        "api/service_pb.js",
        "api/service_pb.d.ts",
        "gen/message.pb.go",
        "gen/message.pb.cc",
        "gen/message.pb.h",
        "static/app.min.js",
        "static/app.min.css",
        "lib/model.freezed.dart",
        "lib/Thing.designer.cs",
    ] {
        assert_eq!(
            classify_of(name),
            Classification::Generated,
            "`{name}` must be recognised as generated from its name"
        );
    }
}

#[test]
fn a_file_with_no_generated_marker_in_its_name_is_not_generated_by_name() {
    assert_eq!(classify_of("src/schema.py"), Classification::Source);
    assert_eq!(classify_of("static/app.js"), Classification::Source);
    // The near-misses that a substring implementation gets wrong.
    assert_eq!(classify_of("src/minimal.js"), Classification::Source);
    assert_eq!(classify_of("src/generics.go"), Classification::Source);
    assert_eq!(classify_of("src/draft.ts"), Classification::Source);
}

// --- Rule 5 and 6: test code --------------------------------------------------------------------

#[test]
fn a_test_directory_makes_the_file_a_test() {
    assert_eq!(classify_of("tests/test_api.py"), Classification::Test);
    assert_eq!(
        classify_of("src/__tests__/render.tsx"),
        Classification::Test
    );
    assert_eq!(classify_of("e2e/checkout.spec.js"), Classification::Test);
}

#[test]
fn a_test_file_name_makes_the_file_a_test() {
    for name in [
        "src/api_test.go",
        "src/api_tests.py",
        "src/api_spec.rb",
        "test_helper.rb",
        "src/widget.test.tsx",
        "src/widget.spec.js",
        "conftest.py",
    ] {
        assert_eq!(
            classify_of(name),
            Classification::Test,
            "`{name}` must be recognised as a test from its name"
        );
    }
}

#[test]
fn a_name_that_merely_contains_test_is_not_a_test() {
    // This is the reason rule 6 requires a word boundary. `latest.rs` misclassified as test code is
    // invisible in a large repository, and it is the most common false positive a naive
    // `contains("test")` produces.
    assert_eq!(classify_of("src/latest.rs"), Classification::Source);
    assert_eq!(classify_of("src/attestation.py"), Classification::Source);
    assert_eq!(classify_of("src/protest.py"), Classification::Source);
    assert_eq!(classify_of("src/manifest.py"), Classification::Source);
}

#[test]
fn a_source_file_named_test_is_source() {
    // `Test` is a directory name, and directories do not classify files by their own name.
    assert_eq!(classify_of("src/test.rs"), Classification::Source);
}

// --- Ordering and the end-to-end result ---------------------------------------------------------

#[test]
fn generated_wins_over_test() {
    // Rule 3 and 4 precede rule 5. Generated content inside a test directory is still generated
    // content, and an agent told to ignore generated files should be told to ignore this one.
    assert_eq!(
        classify_with("tests/fixture_pb2.py", "VALUE = 1"),
        Classification::Generated
    );
    assert_eq!(
        classify_of("tests/schema_pb2.py"),
        Classification::Generated
    );
}

#[test]
fn only_source_is_project_code() {
    assert!(Classification::Source.is_project_code());
    assert!(!Classification::Generated.is_project_code());
    assert!(!Classification::Vendored.is_project_code());
    // Test code is the project's code, but not the code an agent is usually asking about. The
    // distinction is named so it cannot drift between call sites.
    assert!(!Classification::Test.is_project_code());
}

#[test]
fn classification_survives_the_walk() {
    // The pure rules above prove the table; this proves the walk applies it and reports it.
    let discovery = discover_fixture();

    let classified = |wanted: &str| {
        discovery
            .files()
            .iter()
            .find(|file| file.path.as_str() == wanted)
            .map(|file| file.classification)
    };

    assert_eq!(classified("src/main.rs"), Some(Classification::Source));
    assert_eq!(
        classified("src/Legacy.rs"),
        Some(Classification::Source),
        "classification must not depend on the file's case"
    );
    assert_eq!(
        classified("vendor/lib/helper.rs"),
        Some(Classification::Vendored)
    );
    assert_eq!(
        classified("src/gen/models.rs"),
        Some(Classification::Generated)
    );
    assert_eq!(
        classified("src/schema_pb2.py"),
        Some(Classification::Generated)
    );
    assert_eq!(classified("tests/test_api.py"), Some(Classification::Test));
}

#[test]
fn the_by_classification_breakdown_adds_up() {
    // `doctor` reports this breakdown, so it has to be the sum of the files actually yielded, not
    // an independent count.
    let discovery = discover_fixture();
    let stats = discovery.stats();

    let total: usize = stats.by_classification.values().sum();
    assert_eq!(
        total, stats.files_yielded,
        "by_classification must account for every yielded file"
    );
    assert!(
        stats
            .by_classification
            .contains_key(&Classification::Vendored),
        "the fixture has a vendor/ tree, so the breakdown must mention it: {:?}",
        stats.by_classification
    );
    assert!(
        !contains(discovery.files(), "src/api.generated.rs"),
        "the ignored generated file must not appear in the breakdown either"
    );
}
