//! Symlink policy: the three branches, each tested.
//!
//! Cortex read `walkdir`'s symlink metadata, so `is_file()` was false for a symlink to a source
//! file and the file was never indexed — a monorepo sharing code by symlink indexed partially and
//! invisibly. The three branches below are the three things that defect could have been, and each
//! is asserted separately because each can regress independently.

use super::support::{TempTree, contains};
use crate::discover::{DiscoveryOptions, FileDiscovery, SymlinkPolicy, WalkIssueReason};

/// Branch 1: a file symlink resolving inside the repository is followed and indexed.
///
/// This is the fix for the Cortex defect. The monorepo layout this enables — a shared package
/// linked into several crates — is why following is the default rather than skipping.
#[test]
fn a_file_symlink_inside_the_root_is_followed() {
    let root = TempTree::new("symlink-inside");
    root.file("shared/parser.rs", "pub fn parse() {}");
    root.file("crates/app/main.rs", "fn main() {}");
    root.symlink("crates/app/parser.rs", "shared/parser.rs")
        .expect("create symlink");

    let discovery = FileDiscovery::new(root.path(), DiscoveryOptions::default())
        .discover()
        .expect("discover");

    assert!(
        contains(discovery.files(), "crates/app/parser.rs"),
        "a symlink to a source file inside the root must be indexed at its link path"
    );
    assert!(
        contains(discovery.files(), "shared/parser.rs"),
        "the target is still indexed at its own path; both are real files as far as an agent is concerned"
    );
    assert_eq!(discovery.stats().symlinks_followed, 1);
    assert_eq!(discovery.stats().symlink_escapes, 0);
}

/// The linked file carries the target's real content, so a symlink is not an index of a stub.
#[test]
fn a_followed_symlink_carries_the_targets_content() {
    let root = TempTree::new("symlink-content");
    root.file("real/thing.rs", "// @generated by a tool\npub fn f() {}\n");
    root.symlink("alias/thing.rs", "real/thing.rs")
        .expect("create symlink");

    let discovery = FileDiscovery::new(root.path(), DiscoveryOptions::default())
        .discover()
        .expect("discover");

    let linked = discovery
        .files()
        .iter()
        .find(|file| file.path.as_str() == "alias/thing.rs")
        .expect("the symlink must be indexed");
    let target = discovery
        .files()
        .iter()
        .find(|file| file.path.as_str() == "real/thing.rs")
        .expect("the target must be indexed");

    assert_eq!(
        linked.classification, target.classification,
        "classification reads the target's bytes, not the link's"
    );
    assert_eq!(linked.size_bytes, target.size_bytes);
}

/// Branch 2: a symlink resolving outside the repository root is refused.
///
/// This is a path-traversal risk, not a style question. An indexer that can be walked out of the
/// repository by a file it did not write reads files the user never asked about, and an agent
/// driven by the resulting index can be walked out too.
#[test]
fn a_symlink_escaping_the_root_is_refused() {
    let root = TempTree::new("symlink-escape");
    let outside = TempTree::new("symlink-outside");
    outside.file(
        "secret.rs",
        "// not part of the repository\npub fn secret() {}",
    );

    root.file("src/main.rs", "fn main() {}");
    root.escape_link("src/leak.rs", &outside.path().join("secret.rs"))
        .expect("create escaping symlink");

    let discovery = FileDiscovery::new(root.path(), DiscoveryOptions::default())
        .discover()
        .expect("discover");

    assert!(
        !contains(discovery.files(), "src/leak.rs"),
        "a symlink out of the repository must not be indexed"
    );
    assert!(
        contains(discovery.files(), "src/main.rs"),
        "refusing one escape must not stop the walk"
    );
    assert_eq!(discovery.stats().symlink_escapes, 1);

    let escape = discovery
        .issues()
        .iter()
        .find(|issue| issue.path == "src/leak.rs")
        .expect("the refusal must be reported, not silent");
    assert!(
        matches!(escape.reason, WalkIssueReason::SymlinkEscapes { .. }),
        "the issue must name the reason: {:?}",
        escape.reason
    );
}

/// A relative escape is refused too. The containment check runs on canonical paths, so `..` cannot
/// smuggle a link out.
#[test]
fn a_relative_symlink_escaping_the_root_is_refused() {
    let root = TempTree::new("symlink-relative-escape");
    if !root.can_create_symlinks() {
        eprintln!("skipping: this environment cannot create symlinks (Windows needs Developer Mode)");
        return;
    }
    root.file("src/main.rs", "fn main() {}");

    // From `src/`, `../..` reaches the parent of the tree — the system temp directory, which
    // certainly exists and is certainly not the root. The link points at a directory, so a walker
    // that resolved it before checking containment would be escaping *and* recursing.
    root.raw_directory_symlink("src/up", "../..")
        .expect("create relative escape");

    let discovery = FileDiscovery::new(root.path(), DiscoveryOptions::default())
        .discover()
        .expect("discover");

    assert_eq!(
        discovery.stats().symlink_escapes,
        1,
        "a relative link resolving above the root must be refused as an escape"
    );
    assert!(
        !contains(discovery.files(), "src/up/main.rs"),
        "nothing under the escaping link may be indexed"
    );
    assert!(contains(discovery.files(), "src/main.rs"));
}

/// Branch 3: a directory symlink is never descended into, so a cycle is impossible by construction.
///
/// A cycle is not hypothetical: a `.venv` that links back to the project, or `node_modules/self`,
/// are both real. A depth limit does not fix that, it only moves the point at which the walk
/// fails.
#[test]
fn a_directory_symlink_is_not_descended_into() {
    let root = TempTree::new("symlink-dir");
    root.file("src/main.rs", "fn main() {}");
    root.dir("real/inner");
    root.file("real/inner/deep.rs", "pub fn deep() {}");

    root.directory_symlink("link", "real")
        .expect("create directory symlink");

    let discovery = FileDiscovery::new(root.path(), DiscoveryOptions::default())
        .discover()
        .expect("discover");

    assert_eq!(
        discovery.stats().symlink_directories_skipped,
        1,
        "the directory symlink must be counted"
    );
    assert!(
        !contains(discovery.files(), "link/inner/deep.rs"),
        "a directory symlink must not contribute files at its link path"
    );
    assert!(
        contains(discovery.files(), "real/inner/deep.rs"),
        "the target is still reachable through its real path, so nothing is lost"
    );
}

/// A genuine cycle terminates. `loop -> .` is the minimal version and would hang a walker that
/// followed links without a guard.
#[test]
fn a_self_referential_directory_symlink_terminates() {
    let root = TempTree::new("symlink-cycle");
    root.file("src/main.rs", "fn main() {}");
    root.directory_symlink("src/loop", "src")
        .expect("create a link from a directory to its own parent");

    let discovery = FileDiscovery::new(root.path(), DiscoveryOptions::default())
        .discover()
        .expect("a cycle must terminate, not hang");

    assert!(contains(discovery.files(), "src/main.rs"));
    assert_eq!(discovery.stats().symlink_directories_skipped, 1);
}

/// A broken symlink is counted, not fatal. One bad file must never abort a repository.
#[test]
fn a_broken_symlink_is_reported_not_fatal() {
    let root = TempTree::new("symlink-broken");
    root.file("src/main.rs", "fn main() {}");
    root.symlink("src/dangling.rs", "does/not/exist.rs")
        .expect("create broken symlink");

    let discovery = FileDiscovery::new(root.path(), DiscoveryOptions::default())
        .discover()
        .expect("discover");

    assert!(contains(discovery.files(), "src/main.rs"));
    assert!(
        !contains(discovery.files(), "src/dangling.rs"),
        "a broken symlink has no content to index"
    );
    assert_eq!(discovery.stats().unreadable, 1);
    assert!(
        discovery
            .issues()
            .iter()
            .any(|issue| matches!(issue.reason, WalkIssueReason::UnresolvableSymlink { .. })),
        "a broken symlink must be reported: {:?}",
        discovery.issues()
    );
}

/// The strict policy is available and is itself countable, so a caller choosing it can see what it
/// cost.
#[test]
fn the_skip_policy_indexes_nothing_through_a_symlink() {
    let root = TempTree::new("symlink-skip");
    root.file("real/thing.rs", "pub fn f() {}");
    root.symlink("alias/thing.rs", "real/thing.rs")
        .expect("create symlink");

    let options = DiscoveryOptions::default().with_symlinks(SymlinkPolicy::Skip);
    let discovery = FileDiscovery::new(root.path(), options)
        .discover()
        .expect("discover");

    assert!(
        !contains(discovery.files(), "alias/thing.rs"),
        "the skip policy must index nothing through a symlink"
    );
    assert!(contains(discovery.files(), "real/thing.rs"));
    assert_eq!(discovery.stats().symlink_skipped, 1);
    assert_eq!(discovery.stats().symlinks_followed, 0);
}

/// The default is asserted, not assumed. A silent change of this default would quietly restore
/// Cortex's defect.
#[test]
fn the_default_policy_follows_files_inside_the_root() {
    assert_eq!(
        SymlinkPolicy::default(),
        SymlinkPolicy::FollowFilesInsideRoot
    );
    assert_eq!(
        DiscoveryOptions::default().symlinks(),
        SymlinkPolicy::FollowFilesInsideRoot
    );
}
